### ISSUE TITLE
Pagina top jucatori

### ISSUE THREAD

**Issue by alexandru-atanasiu** [allexx2200/Dr.-Jekyll-and-Mr.-Hyde#19]

**Comment by zahariadaniel16** [comment]
Cam asta ar fi leaderboard-ul. Dar nu reusesc sa imi trag si sa modific numele, scorurile.. inca mai studiez. Daca aveti vreo idee?!..

[Score.zip](https://github.com/allexx2200/Dr.-Jekyll-and-Mr.-Hyde/files/598397/Score.zip)
