### ISSUE TITLE
Cercetare algoritm de generare labirint aleator

### ISSUE THREAD

**Issue by alexandru-atanasiu** [allexx2200/Dr.-Jekyll-and-Mr.-Hyde#2]
Cercetare pe algoritmi de generare labirint aleator, studiu problema, posibile solutii, idei de implementare pentru problema noastra

**Comment by CristinaMan** [comment]
wall = 3
path = 7
3 quarter variations -> combine in final matrix
until tuesday

**Comment by alexandru-atanasiu** [comment]
TODO: de facut 3 variatii pentru sferturi
